import foreign "rain_exc_error" as error
import foreign "rain_exc_arg_mismatch" as arg_mismatch
import foreign "rain_exc_fpe" as fpe
import foreign "rain_exc_interrupt" as interrupt
import foreign "rain_exc_segfault" as segfault
import foreign "rain_exc_uncallable" as uncallable

error = table
error.msg = "error"

arg_mismatch = table from error
arg_mismatch.msg = "argument mismatch"

uncallable = table from error
uncallable.msg = "uncallable value"

interrupt = table from error
interrupt.msg = "received interrupt signal"

fpe = table from error
fpe.msg = "floating point error"

segfault = table from error
segfault.msg = "segmentation fault"

let safe = func(val)
  while val is table
    break if !(val.metatable)
    val = val.metatable

  return val != error
